name: DeepForest_dask
channels:
  - defaults
dependencies:
  - python=3.6
  - sphinx
  - pyyaml
  - pytest
  - numpydoc
  - cython
  - h5py
  - xmltodict
  - keras>= 2.3.0
  - tqdm
  - numpy
  - pillow
  - scipy
  - pip
  - matplotlib
  - sphinx_rtd_theme
  - pandas
  - pip:
    - keras-resnet
    - opencv-python
    - slidingwindow
    - git+https://github.com/Weecology/DeepForest
    - git+https://github.com/bw4sz/keras-retinanet


